x-bot-base: &bot-base
  build:
    context: ./bot
    dockerfile: Dockerfile
  image: ms-helper-bot:prod
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pgrep -f main.py || exit 1"]
    interval: 1m
    timeout: 10s
    retries: 3

services:
  bot-office-helper:
    <<: *bot-base
    container_name: bot-office-helper
    env_file:
      - ./envs/office365.env
    volumes:
      - ./users/office365/office-helper:/data:rw
      - ./users/office365:/shared:rw
    networks:
      vps-net:
        ipv4_address: ${OFFICE_HELPER_IP}
        mac_address: ${OFFICE_HELPER_MAC}

  bot-office-tester:
    <<: *bot-base
    container_name: bot-office-tester
    env_file:
      - ./envs/officetester.env
    volumes:
      - ./users/office365/officetester:/data:rw
      - ./users/office365:/shared:rw
    networks:
      vps-net:
        ipv4_address: ${OFFICETESTER_IP}
        mac_address: ${OFFICETESTER_MAC}

networks:
  vps-net:
    driver: ${NETWORK_DRIVER}
    driver_opts:
      parent: ${PARENT_INTERFACE}
    ipam:
      driver: default
      config:
        - subnet:   ${SUBNET}
          gateway:  ${GATEWAY}
          ip_range: ${IP_RANGE}
